import argparse

parser = argparse.ArgumentParser('Set Attention BiLSTM temporal detector', add_help=False)
parser.add_argument('--lr', default=1e-4, type=float)
parser.add_argument('--batch_size', default=32, type=int)
parser.add_argument('--grad_accum_steps', default=1, type=int)
parser.add_argument('--val_batch_size', default=8, type=int)
parser.add_argument('--weight_decay', default=1e-4, type=float)
parser.add_argument('--epoch', default=200, type=int)
parser.add_argument('--lr_drop', default=200, type=int)
parser.add_argument('--lr_scheduler', default='plateau', choices=('plateau', 'step', 'none'))
parser.add_argument('--plateau_metric', default='MPJPE', choices=('MPJPE', 'MPJDLE', 'loss'))
parser.add_argument('--plateau_factor', default=0.5, type=float)
parser.add_argument('--plateau_patience', default=5, type=int)
parser.add_argument('--plateau_min_lr', default=1e-6, type=float)
parser.add_argument('--early_stop_patience', default=10, type=int)
parser.add_argument('--clip_max_norm', default=0.1, type=float)
parser.add_argument('--mode', default=True)
parser.add_argument('--backbone_name', type=str, default='resnet18')
parser.add_argument('--backbone_pretrain', dest='backbone_pretrain', action='store_true')
parser.add_argument('--no_backbone_pretrain', dest='backbone_pretrain', action='store_false')
parser.set_defaults(backbone_pretrain=True)
parser.add_argument('--frozen_weights', type=str, default=None)
parser.add_argument('--dilation', action='store_true')
parser.add_argument('--position_embedding', default='learned', type=str, choices=('sine', 'learned'))
parser.add_argument('--enc_layers', default=6, type=int)
parser.add_argument('--dec_layers', default=6, type=int)
parser.add_argument('--dim_feedforward', default=2048, type=int)
parser.add_argument('--hidden_dim', default=256, type=int)
parser.add_argument('--dropout', default=0.1, type=float)
parser.add_argument('--nheads', default=8, type=int)
parser.add_argument('--num_queries', default=100, type=int)
parser.add_argument('--pre_norm', action='store_true')
parser.add_argument('--masks', action='store_true')
parser.add_argument('--no_aux_loss', dest='aux_loss', action='store_false')
parser.add_argument('--set_cost_class', default=5, type=float)
parser.add_argument('--set_cost_kpt', default=25, type=float)
parser.add_argument('--set_cost_id', default=2, type=float)
parser.add_argument('--cls_loss_coef', default=1, type=float)
parser.add_argument('--kpt_loss_coef', default=5, type=float)
parser.add_argument('--id_loss_coef', default=2, type=float)
parser.add_argument('--dataset_root', default='./data')
parser.add_argument('--dataset_root_kpt', default='./data')
parser.add_argument('--remove_difficult', action='store_true')
parser.add_argument('--output_dir', default='')
parser.add_argument('--device', default='cuda')
parser.add_argument('--seed', default=42, type=int)
parser.add_argument('--resume', default='')
parser.add_argument('--start_epoch', default=0, type=int, metavar='N')
parser.add_argument('--eval', action='store_true', default=False)
parser.add_argument('--num_workers', default=8, type=int)
parser.add_argument('--prefetch_factor', default=4, type=int)
parser.add_argument('--amp', dest='amp', action='store_true')
parser.add_argument('--no_amp', dest='amp', action='store_false')
parser.set_defaults(amp=False)
parser.add_argument('--compile', dest='compile', action='store_true')
parser.add_argument('--no_compile', dest='compile', action='store_false')
parser.set_defaults(compile=False)
parser.add_argument('--matmul_precision', default='high', choices=('highest', 'high', 'medium'))
parser.add_argument('--pin_memory', dest='pin_memory', action='store_true')
parser.add_argument('--no_pin_memory', dest='pin_memory', action='store_false')
parser.set_defaults(pin_memory=True)
parser.add_argument('--persistent_workers', dest='persistent_workers', action='store_true')
parser.add_argument('--no_persistent_workers', dest='persistent_workers', action='store_false')
parser.set_defaults(persistent_workers=True)
parser.add_argument('--mem_stats', action='store_true', default=False)
parser.add_argument('--mem_stats_save', default='./experiments/mem_stats_attn_bilstm/')
parser.add_argument('--mem_stats_every', default=1, type=int)
parser.add_argument(
    '--cfar_mode',
    default='none',
    choices=('none', 'os2d'),
    help='Select raw mmwave data or a matching offline CFAR dataset under dataset_root/mmwave_cfar/.',
)
parser.add_argument('--cfar_guard', default=1, type=int)
parser.add_argument('--cfar_train', default=4, type=int)
parser.add_argument('--cfar_rank_ratio', default=0.75, type=float)
parser.add_argument('--cfar_pfa', default=1e-3, type=float)
parser.add_argument('--cfar_soft_mode', default='subtract', choices=('subtract', 'mask'))
parser.add_argument('--cfar_split_halves', dest='cfar_split_halves', action='store_true')
parser.add_argument('--no_cfar_split_halves', dest='cfar_split_halves', action='store_false')
parser.set_defaults(cfar_split_halves=True)
parser.add_argument('--attn_temporal_layers', default=2, type=int)
parser.add_argument('--query_refine_layers', default=2, type=int)
parser.add_argument('--bilstm_layers', default=1, type=int)
parser.add_argument('--bilstm_hidden_dim', default=256, type=int)

args, _ = parser.parse_known_args()
