name: mmvr-py310
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - numpy
  - scipy
  - pandas
  - matplotlib
  - h5py
  - pip:
      - -r requirements_mamba.txt
